import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, BookOpen, MapPin } from 'lucide-react';
import { getPublishedBlogs } from '@/lib/blog';

export const metadata = { title: 'Kumaon travel journal', description: 'Local guides, thoughtful itineraries, and the best things to do around Bhimtal and Kainchi Dham.' };

export default async function Blog() {
  const blogs = await getPublishedBlogs();
  return <div className="mx-auto max-w-5xl px-5 py-14 md:py-20"><p className="sans flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-[#b66b45]"><BookOpen size={15} /> The pahadi journal</p><h1 className="mt-3 text-5xl text-[#173f35] md:text-6xl">Notes from the road.</h1><p className="sans mt-5 max-w-xl text-base leading-7 text-[#607067]">Local knowledge for slower mornings, better stays, and more thoughtful trips through Kumaon.</p><div className="mt-10 grid gap-5">{blogs.map((blog) => <Link href={`/blog/${blog.slug}`} key={blog.slug} className="group overflow-hidden rounded-[1.75rem] border border-[#dfe3d8] bg-white shadow-[0_14px_40px_rgba(23,63,53,.06)] transition hover:-translate-y-1 hover:shadow-[0_20px_45px_rgba(23,63,53,.12)]">{blog.featuredImage && <div className="relative aspect-[2.2/1]"><Image src={blog.featuredImage} alt={blog.imageAltText || blog.title} fill sizes="(max-width: 768px) 92vw, 800px" className="object-cover" /></div>}<div className="p-6 md:p-8"><div className="flex flex-wrap items-center gap-3 sans text-xs font-bold uppercase tracking-[.15em] text-[#b66b45]"><span>{blog.category}</span><span>·</span><span>{blog.authorName}</span>{blog.publishedAt && <><span>·</span><span>{new Date(blog.publishedAt).toLocaleDateString('en-IN', { dateStyle: 'medium' })}</span></>}</div><h2 className="mt-4 max-w-2xl text-3xl text-[#173f35] md:text-4xl">{blog.title}</h2><p className="sans mt-3 max-w-2xl text-base leading-7 text-[#607067]">{blog.excerpt}</p><span className="mt-6 inline-flex items-center gap-2 sans text-sm font-bold text-[#24584a]">Read the guide <ArrowUpRight size={17} /></span></div></Link>)}</div><div className="mt-10 flex items-center gap-2 rounded-2xl bg-[#e7eadf] p-5 sans text-sm text-[#526057]"><MapPin size={18} className="text-[#b66b45]" /> Guides are written for Bhimtal, Kainchi Dham, and the Kumaon roads between them.</div></div>;
}
