ALTER TABLE `Listing`
    ADD COLUMN `address` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `details` JSON NULL,
    ADD COLUMN `seoTitle` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `seoDescription` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `cancellationPolicy` VARCHAR(191) NOT NULL DEFAULT 'FLEXIBLE',
    ADD COLUMN `featured` BOOLEAN NOT NULL DEFAULT false;