import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';
import Image from 'next/image';

const display = { variable: '' };
const sans = { variable: '' };


export const metadata: Metadata = { title: { default: 'KainchiDarshan | See Kumaon differently', template: '%s | KainchiDarshan' }, description: 'Thoughtfully chosen stays, rides and experiences around Bhimtal and Kainchi Dham.', metadataBase: new URL('http://localhost:3000'), icons: { icon: '/images/Logo.png', shortcut: '/images/Logo.png' } };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <html lang="en" className={`${display.variable} ${sans.variable}`}><body><header className="site-header sans"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:py-5"><Link href="/" aria-label="KainchiDarshan home"><Image src="/images/Logo.png" alt="Kainchi Darshan" width={210} height={80} priority className="h-14 w-auto object-contain" /></Link><nav className="hidden items-center gap-8 text-sm text-white/85 md:flex"><Link href="/stays">Stays</Link><Link href="/rides">Rides</Link><Link href="/rentals">Rentals</Link><Link href="/activities">Experiences</Link></nav><div className="flex items-center gap-3 text-sm"><Link href="/partner/login" className="hidden text-white/85 md:block">List your place</Link><Link href="/login" className="rounded-full border border-white/35 px-3 py-2 text-white md:px-4">Sign in</Link><details className="mobile-menu relative md:hidden"><summary className="flex h-10 w-10 cursor-pointer list-none items-center justify-center rounded-full border border-white/35 text-lg" aria-label="Open navigation"><span aria-hidden="true">☰</span></summary><nav className="absolute right-0 top-12 z-30 grid min-w-48 gap-1 rounded-2xl border border-white/20 bg-[#173f35]/95 p-2 text-sm text-white shadow-2xl backdrop-blur"><Link href="/stays">Stays</Link><Link href="/rides">Rides</Link><Link href="/rentals">Rentals</Link><Link href="/activities">Experiences</Link><Link href="/partner/login">List your place</Link></nav></details></div></div></header><main>{children}</main><footer className="sans mt-20 bg-[#173f35] px-5 py-14 text-[#f7f4ec]"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-3"><div><Image src="/images/Logo.png" alt="Kainchi Darshan" width={210} height={80} className="h-14 w-auto object-contain" /><p className="mt-3 max-w-xs text-sm leading-6 text-white/60">A slower, more thoughtful way to see Kumaon.</p></div><div><p className="mb-3 text-[10px] font-bold uppercase tracking-[.24em] text-[#d6a06d]">Explore</p><div className="grid gap-2 text-sm text-white/75"><Link href="/stays">Stays around Bhimtal</Link><Link href="/packages">Curated packages</Link><Link href="/about">Our story</Link></div></div><div><p className="mb-3 text-[10px] font-bold uppercase tracking-[.24em] text-[#d6a06d]">Need a hand?</p><p className="text-sm leading-6 text-white/75">hello@pahadi.stay<br/>+91 98765 43210</p></div></div></footer></body></html>;
}
