export type Listing = { slug:string; title:string; location:string; price:number; rating:number; category:'stay'|'rental'|'activity'; image:string; images?: string[]; description:string; amenities:string[]; facilities?: Record<string, boolean>; faqs?: { question: string; answer: string }[]; houseRules?: { title: string; text: string }[] };
export type Rental = { slug:string; title:string; type:string; price:number; image:string; description:string; features:string[]; pickup:string; bikeQuantity?: number; scootyQuantity?: number };
export const stays: Listing[] = [
 {slug:'oak-house-bhimtal', title:'Oak House by the Lake', location:'Bhimtal, Uttarakhand', price:4200, rating:4.9, category:'stay', image:'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=1000&q=85', description:'A sun-filled cedar home with lake views, a warm kitchen, and the quiet rhythm of the forest.', amenities:['Lake view','Breakfast included','Bonfire','Wi-Fi'], houseRules:[{title:'Check-in & check-out',text:'Check-in from 14:00. Check-out by 11:00.'},{title:'Pets',text:'No pets allowed — the lake shore is wildlife habitat.'},{title:'Parties & events',text:'No parties or events; this is a quiet neighbourhood.'},{title:'Smoking',text:'No smoking indoors. Designated smoking area at the back deck.'},{title:'Quiet hours',text:'Quiet hours between 22:00 and 07:00 — the lodge neighbours sleep early.'},{title:'Extra guests',text:'Guests may not bring extra people without prior approval from the host.'}]
},
 {slug:'the-kumaon-cabin', title:'The Kumaon Cabin', location:'Kainchi Road, Uttarakhand', price:6800, rating:4.8, category:'stay', image:'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1000&q=85', description:'Minimal mountain architecture, expansive windows, and a private deck above the pines.', amenities:['Valley view','Private deck','Pet friendly','Parking'], houseRules:[{title:'Check-in & check-out',text:'Self check-in with a code. Check-in after 13:00, check-out by 10:00.'},{title:'Pets',text:'Well-behaved dogs are welcome on the deck. Please clean up after them.'},{title:'Parties & events',text:'No indoor events. Small balcony gatherings are fine until 21:00.'},{title:'Smoking',text:'Smoking is allowed on the deck only. Please use the ashtrays provided.'},{title:'Quiet hours',text:'Quiet hours from 22:00 to 08:00 out of respect for the forest surroundings.'},{title:'Extra guests',text:'Occupancy is limited to the listed maximum — no overnight extras without notice.'}]
},
 {slug:'bloomingdale-homestay', title:'Bloomingdale Homestay', location:'Bhowali, Uttarakhand', price:2800, rating:4.7, category:'stay', image:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1000&q=85', description:'A gentle family-run homestay with garden breakfasts and local recommendations.', amenities:['Garden','Home-cooked meals','Hot water','Power backup'], houseRules:[{title:'Check-in & check-out',text:'Check-in from 13:00. Check-out by 11:00. Evening arrival by arrangement.'},{title:'Pets',text:'Two garden cats live here — please do not let dogs roam the flower beds.'},{title:'Parties & events',text:'No parties. The family uses the common rooms in the evenings.'},{title:'Smoking',text:'Smoking is not permitted inside the house or the garden.'},{title:'Quiet hours',text:'Please keep noise down after 21:30 — the family sleeps early.'},{title:'Meals',text:'Breakfast is served at 08:00–09:30. Let the host know if you need a later start.'}]
},
];

export const destinations = [{title:'Bhimtal', sub:'The lake, at its calmest', image:'https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=1200&q=85', slug:'bhimtal'},{title:'Kainchi Dham', sub:'A little closer to wonder', image:'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=85', slug:'kainchi-dham'}];
export const rentals: Rental[] = [
 {slug:'pahadi-scooty', title:'Pahadi Scooty', type:'Automatic scooter', price:500, image:'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85', description:'Easy, light, and ready for lake roads and local errands.', features:['Helmet included','Fuel efficient','Easy pickup'], pickup:'Bhimtal & Bhowali', scootyQuantity:10},
 {slug:'pahadi-bike', title:'Pahadi Bike', type:'Mountain motorcycle', price:800, image:'https://images.unsplash.com/photo-1558980664-10ea6f5e9b8f?auto=format&fit=crop&w=1200&q=85', description:'A confident ride for winding roads, temple visits, and wider horizons.', features:['Helmet included','Roadside support','Secure parking'], pickup:'Bhimtal & Kainchi Dham', bikeQuantity:10}
];
