export type Listing = { slug:string; title:string; location:string; price:number; rating:number; category:'stay'|'rental'|'activity'; image:string; description:string; amenities:string[] };
export type Rental = { slug:string; title:string; type:string; price:number; image:string; description:string; features:string[]; pickup:string };
export const stays: Listing[] = [
 {slug:'oak-house-bhimtal', title:'Oak House by the Lake', location:'Bhimtal, Uttarakhand', price:4200, rating:4.9, category:'stay', image:'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=1000&q=85', description:'A sun-filled cedar home with lake views, a warm kitchen, and the quiet rhythm of the forest.', amenities:['Lake view','Breakfast included','Bonfire','Wi-Fi']},
 {slug:'the-kumaon-cabin', title:'The Kumaon Cabin', location:'Kainchi Road, Uttarakhand', price:6800, rating:4.8, category:'stay', image:'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1000&q=85', description:'Minimal mountain architecture, expansive windows, and a private deck above the pines.', amenities:['Valley view','Private deck','Pet friendly','Parking']},
 {slug:'bloomingdale-homestay', title:'Bloomingdale Homestay', location:'Bhowali, Uttarakhand', price:2800, rating:4.7, category:'stay', image:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1000&q=85', description:'A gentle family-run homestay with garden breakfasts and local recommendations.', amenities:['Garden','Home-cooked meals','Hot water','Power backup']}
];
export const destinations = [{title:'Bhimtal', sub:'The lake, at its calmest', image:'https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=1200&q=85', slug:'bhimtal'},{title:'Kainchi Dham', sub:'A little closer to wonder', image:'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=85', slug:'kainchi-dham'}];
export const rentals: Rental[] = [
 {slug:'pahadi-scooty', title:'Pahadi Scooty', type:'Automatic scooter', price:500, image:'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85', description:'Easy, light, and ready for lake roads and local errands.', features:['Helmet included','Fuel efficient','Easy pickup'], pickup:'Bhimtal & Bhowali'},
 {slug:'pahadi-bike', title:'Pahadi Bike', type:'Mountain motorcycle', price:800, image:'https://images.unsplash.com/photo-1558980664-10ea6f5e9b8f?auto=format&fit=crop&w=1200&q=85', description:'A confident ride for winding roads, temple visits, and wider horizons.', features:['Helmet included','Roadside support','Secure parking'], pickup:'Bhimtal & Kainchi Dham'}
];
