'use client';
import { useState } from 'react';
import { BarChart3, BookOpen, Check, Edit3, FileText, LayoutDashboard, LogOut, Plus, Save, Settings, ShoppingBag, Sparkles, Trash2, Users } from 'lucide-react';
import { rentals, stays } from '@/lib/mock-data';
import { ContentManager } from './ContentManager';

type RentalRow = { title: string; price: number; type: string };
type BlogRow = { title: string; slug: string; status: 'Published' | 'Draft'; keyword: string };

export function AdminWorkspace() {
  const [section, setSection] = useState('overview');
  const [rentalRows, setRentalRows] = useState<RentalRow[]>(rentals.map(({ title, price, type }) => ({ title, price, type })));
  const [stayPrices, setStayPrices] = useState(stays.map(({ title, price }) => ({ title, price })));
  const [blogs, setBlogs] = useState<BlogRow[]>([{ title: 'How to spend a quiet morning in Bhimtal', slug: 'quiet-morning-bhimtal', status: 'Published', keyword: 'things to do in Bhimtal' }]);
  const [saved, setSaved] = useState(false);

  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 1800); };
  const nav = [['overview', LayoutDashboard, 'Overview'], ['content', ShoppingBag, 'Manage content'], ['stays', ShoppingBag, 'Stays & prices'], ['rentals', Sparkles, 'Rentals'], ['blogs', BookOpen, 'SEO blog'], ['partners', Users, 'Partners'], ['settings', Settings, 'Settings']] as const;
  return <div className="admin-shell min-h-screen bg-[#f2f4ed] text-[#23332e]"><aside className="hidden border-r border-[#dfe3d8] bg-[#173f35] p-5 text-white lg:block"><div className="mb-12 text-2xl font-semibold">pahadi<span className="text-[#d6a06d]">.</span><small className="mt-2 block sans text-[10px] uppercase tracking-[.2em] text-white/50">Control room</small></div><nav className="grid gap-2">{nav.map(([key, Icon, label]) => <button key={key} onClick={() => setSection(key)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left sans text-sm transition ${section === key ? 'bg-white/15 text-white' : 'text-white/65 hover:bg-white/10 hover:text-white'}`}><Icon size={18}/>{label}</button>)}</nav><button className="mt-12 flex items-center gap-3 px-3 sans text-sm text-white/60"><LogOut size={17}/>Sign out</button></aside><main className="min-w-0"><header className="border-b border-[#dfe3d8] bg-[#f7f4ec] px-5 py-5 md:px-8"><div className="flex items-center justify-between"><div><p className="sans text-xs font-bold uppercase tracking-[.18em] text-[#b66b45]">Admin workspace</p><h1 className="mt-2 text-3xl text-[#173f35]">{nav.find(([key]) => key === section)?.[2]}</h1></div><div className="flex items-center gap-3"><span className="hidden rounded-full bg-[#e2eee7] px-3 py-2 sans text-xs font-bold text-[#24584a] sm:inline-flex"><Check size={14}/> All systems healthy</span><button onClick={save} className="inline-flex items-center gap-2 rounded-full bg-[#b66b45] px-4 py-2.5 sans text-sm font-bold text-white shadow-sm hover:bg-[#9f5938]"><Save size={16}/>{saved ? 'Saved' : 'Save changes'}</button></div></div><div className="mt-5 flex gap-2 overflow-x-auto lg:hidden">{nav.map(([key, Icon, label]) => <button key={key} onClick={() => setSection(key)} className={`inline-flex shrink-0 items-center gap-2 rounded-full px-3 py-2 sans text-xs font-bold ${section === key ? 'bg-[#173f35] text-white' : 'bg-white text-[#24584a]'}`}><Icon size={15}/>{label}</button>)}</div></header><div className="p-5 md:p-8">{section === 'overview' && <Overview setSection={setSection}/>} {section === 'stays' && <PriceTable title="Stay pricing" rows={stayPrices} setRows={setStayPrices} suffix="/ night"/>} {section === 'rentals' && <RentalTable rows={rentalRows} setRows={setRentalRows}/>} {section === 'blogs' && <BlogManager blogs={blogs} setBlogs={setBlogs}/>} {section === 'partners' && <Placeholder title="Partners & approvals" text="Review verification status, partner listings, and payout readiness here."/>} {section === 'settings' && <SettingsPanel/>}</div></main></div>;
}

function Overview({ setSection }: { setSection: (section: string) => void }) { return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['₹3.2L', 'Gross revenue', BarChart3, 'up 14% this month'], ['84', 'Bookings', ShoppingBag, '12 awaiting payment'], ['7', 'Draft content', FileText, '3 blogs need SEO'], ['42', 'Active partners', Users, '2 pending review']].map(([value, label, Icon, note]) => <div className="rounded-2xl border border-[#dfe3d8] bg-white p-5" key={label as string}><div className="flex items-center justify-between"><span className="rounded-xl bg-[#e7eadf] p-2 text-[#24584a]"><Icon size={18}/></span><span className="sans text-xs font-bold text-[#6d8b62]">{note as string}</span></div><p className="mt-6 text-3xl text-[#173f35]">{value as string}</p><p className="sans mt-1 text-sm text-[#6c7770]">{label as string}</p></div>)}</div><div className="mt-8 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-2xl border border-[#dfe3d8] bg-white p-6"><div className="flex items-center justify-between"><div><p className="sans text-xs font-bold uppercase tracking-[.15em] text-[#b66b45]">Revenue pulse</p><h2 className="mt-2 text-2xl text-[#173f35]">A steady month</h2></div><BarChart3 className="text-[#b66b45]"/></div><div className="mt-8 flex h-40 items-end gap-3">{[42, 55, 48, 72, 64, 86, 78, 94, 70, 83, 92, 100].map((height, index) => <div key={index} className="group flex flex-1 flex-col justify-end gap-2"><div className="rounded-t-lg bg-[#24584a] transition group-hover:bg-[#b66b45]" style={{ height: `${height}%` }}/><span className="sans text-center text-[10px] text-[#8a968e]">{index + 1}</span></div>)}</div></div><div className="rounded-2xl border border-[#dfe3d8] bg-[#173f35] p-6 text-white"><Sparkles className="text-[#d6a06d]"/><h2 className="mt-5 text-2xl">Keep the journal moving.</h2><p className="sans mt-3 text-sm leading-6 text-white/65">Fresh destination guides help guests discover Kumaon before they book.</p><button onClick={() => setSection('blogs')} className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#d6a06d] px-4 py-2.5 sans text-sm font-bold text-[#173f35]">Write a blog <Plus size={16}/></button></div></div></>; }

function PriceTable({ title, rows, setRows, suffix }: { title: string; rows: { title: string; price: number }[]; setRows: (rows: { title: string; price: number }[]) => void; suffix: string }) { return <Panel title={title} action="Add stay"><div className="divide-y divide-[#e4e3da]">{rows.map((row, index) => <div className="flex flex-col gap-4 py-5 sm:flex-row sm:items-center sm:justify-between" key={row.title}><div><p className="font-semibold text-[#173f35]">{row.title}</p><p className="sans mt-1 text-xs text-[#6c7770]">Live listing · price visible to guests</p></div><div className="flex items-center gap-3"><label className="sans flex items-center gap-2 rounded-xl border border-[#d6d9d1] bg-[#f7f4ec] px-3 py-2 text-sm"><span className="text-[#6c7770]">₹</span><input type="number" value={row.price} onChange={(event) => setRows(rows.map((item, itemIndex) => itemIndex === index ? { ...item, price: Number(event.target.value) } : item))} className="w-24 bg-transparent font-bold outline-none"/></label><span className="sans text-xs text-[#6c7770]">{suffix}</span><button className="rounded-full p-2 text-[#6c7770] hover:bg-[#e7eadf]" aria-label={`Edit ${row.title}`}><Edit3 size={16}/></button></div></div>)}</div></Panel>; }

function RentalTable({ rows, setRows }: { rows: RentalRow[]; setRows: (rows: RentalRow[]) => void }) { return <Panel title="Rental inventory" action="Add rental"><div className="grid gap-4 md:grid-cols-2">{rows.map((row, index) => <div className="rounded-2xl border border-[#e4e3da] p-5" key={row.title}><div className="flex items-start justify-between"><div><p className="sans text-xs font-bold uppercase tracking-[.14em] text-[#b66b45]">{row.type}</p><h2 className="mt-2 text-2xl text-[#173f35]">{row.title}</h2></div><Edit3 size={17} className="text-[#6c7770]"/></div><div className="mt-6 flex items-center justify-between"><label className="sans flex items-center gap-2 rounded-xl border border-[#d6d9d1] bg-[#f7f4ec] px-3 py-2 text-sm"><span>₹</span><input type="number" value={row.price} onChange={(event) => setRows(rows.map((item, itemIndex) => itemIndex === index ? { ...item, price: Number(event.target.value) } : item))} className="w-20 bg-transparent font-bold outline-none"/></label><span className="sans text-xs text-[#6c7770]">per day</span></div></div>)}</div></Panel>; }

function BlogManager({ blogs, setBlogs }: { blogs: BlogRow[]; setBlogs: (blogs: BlogRow[]) => void }) { return <><Panel title="SEO content studio" action="New blog"><div className="mb-6 rounded-2xl bg-[#e7eadf] p-5"><div className="flex items-start gap-3"><Sparkles className="mt-1 text-[#b66b45]" size={19}/><div><p className="font-semibold text-[#173f35]">Grow organic discovery</p><p className="sans mt-1 text-sm leading-6 text-[#526057]">Every post gets a clean URL, target keyword, meta description, and publish state.</p></div></div></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead className="sans border-b border-[#e4e3da] text-xs uppercase tracking-[.12em] text-[#6c7770]"><tr><th className="pb-3">Article</th><th className="pb-3">Keyword</th><th className="pb-3">Status</th><th className="pb-3">Actions</th></tr></thead><tbody>{blogs.map((blog, index) => <tr className="border-b border-[#e4e3da] last:border-0" key={blog.slug}><td className="py-5 font-semibold text-[#173f35]">{blog.title}<span className="mt-1 block sans text-xs font-normal text-[#6c7770]">/{blog.slug}</span></td><td className="py-5 sans text-sm text-[#526057]">{blog.keyword}</td><td className="py-5"><span className="rounded-full bg-[#e2eee7] px-3 py-1 sans text-xs font-bold text-[#24584a]">{blog.status}</span></td><td className="py-5"><button onClick={() => setBlogs(blogs.filter((_, itemIndex) => itemIndex !== index))} className="rounded-full p-2 text-[#6c7770] hover:bg-[#fff0e8] hover:text-[#9f5938]" aria-label={`Delete ${blog.title}`}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div></Panel><div className="mt-6 grid gap-5 md:grid-cols-3">{[['Target keyword', 'things to do in Bhimtal'], ['Meta description', 'Plan a thoughtful Bhimtal trip with local stays, rides and quiet experiences.'], ['Internal linking', '3 links recommended']].map(([label, value], index) => <div className="rounded-2xl border border-[#dfe3d8] bg-white p-5" key={label}><p className="sans text-xs font-bold uppercase tracking-[.12em] text-[#6c7770]">{label}</p><p className="mt-3 text-lg text-[#173f35]">{value}</p><button className="mt-4 inline-flex items-center gap-2 sans text-xs font-bold text-[#b66b45]"><Edit3 size={14}/> Edit</button></div>)}</div></>; }

function Panel({ title, action, children }: { title: string; action: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-[#dfe3d8] bg-white p-5 md:p-7"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl text-[#173f35]">{title}</h2><button className="inline-flex items-center gap-2 rounded-full border border-[#d6d9d1] px-3 py-2 sans text-xs font-bold text-[#24584a] hover:bg-[#e7eadf]"><Plus size={15}/>{action}</button></div>{children}</section>; }
function Placeholder({ title, text }: { title: string; text: string }) { return <Panel title={title} action="Add"><div className="rounded-2xl bg-[#f7f4ec] p-8 text-center"><FileText className="mx-auto text-[#b66b45]"/><p className="mt-4 text-xl text-[#173f35]">{text}</p></div></Panel>; }
function SettingsPanel() { return <Panel title="Admin settings" action="Save"><div className="grid gap-5 md:grid-cols-2"><div><label className="sans text-sm font-bold text-[#173f35]">Admin email allowlist</label><textarea className="mt-2 min-h-28 w-full rounded-xl border border-[#d6d9d1] bg-[#f7f4ec] p-3 sans text-sm" defaultValue="admin@pahadi.stay\nfounder@pahadi.stay\noperations@pahadi.stay"/><p className="mt-2 sans text-xs text-[#6c7770]">Only these emails can enter the admin area.</p></div><div><label className="sans text-sm font-bold text-[#173f35]">Default commission</label><input type="number" defaultValue="10" className="mt-2 w-full rounded-xl border border-[#d6d9d1] bg-[#f7f4ec] p-3 sans text-sm"/><p className="mt-2 sans text-xs text-[#6c7770]">Applied to new partner listings.</p></div></div></Panel>; }
