'use client';

import { useEffect, useState } from 'react';

type Vehicle = { id: string; type: string; registrationNumber: string; driverName: string };
type Pickup = { id: string; pickupLocationText: string; requestedTime: string; booking: { trip: { reference: string }; listing: { title: string } } };

export function PickupManager() {
  const [pickups, setPickups] = useState<Pickup[]>([]); const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [message, setMessage] = useState('Loading pickup requests...'); const [busy, setBusy] = useState('');
  const load = async () => { const [pickupResponse, vehicleResponse] = await Promise.all([fetch('/api/admin/pickup-requests'), fetch('/api/admin/vehicles')]); if (!pickupResponse.ok || !vehicleResponse.ok) { setMessage('Could not load pickup operations.'); return; } setPickups(await pickupResponse.json()); setVehicles(await vehicleResponse.json()); setMessage(''); };
  useEffect(() => { load(); }, []);
  const assign = async (pickupId: string, vehicleId: string) => { if (!vehicleId) return; setBusy(pickupId); const response = await fetch(`/api/admin/pickup-requests/${pickupId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ vehicleId }) }); setBusy(''); if (!response.ok) { setMessage('Could not assign that vehicle.'); return; } setPickups((current) => current.filter((pickup) => pickup.id !== pickupId)); };
  return <section className="rounded-2xl border border-[#dfe3d8] bg-white p-5 md:p-7"><div className="flex items-center justify-between gap-3"><div><p className="sans text-xs font-bold uppercase tracking-[.16em] text-[#b66b45]">Operations</p><h2 className="mt-2 text-2xl text-[#173f35]">Pending pickups</h2></div><span className="rounded-full bg-[#fff0e8] px-3 py-1 sans text-xs font-bold text-[#9f5938]">{pickups.length} unassigned</span></div>{message && <p className="mt-4 sans text-sm text-[#6c7770]">{message}</p>}<div className="mt-5 divide-y divide-[#e4e3da]">{pickups.map((pickup) => { const urgent = new Date(pickup.requestedTime).getTime() - Date.now() <= 3 * 3600000; return <div key={pickup.id} className="flex flex-col gap-3 py-4 md:flex-row md:items-center md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-[#173f35]">{pickup.booking.listing.title}</strong>{urgent && <span className="rounded-full bg-[#c84b3d] px-2 py-1 sans text-[10px] font-bold uppercase text-white">Within 3 hours</span>}</div><p className="mt-1 sans text-sm text-[#6c7770]">{pickup.booking.trip.reference} · {pickup.pickupLocationText} · {new Date(pickup.requestedTime).toLocaleString('en-IN')}</p></div><select disabled={busy === pickup.id} defaultValue="" onChange={(event) => assign(pickup.id, event.target.value)} className="rounded-xl border border-[#d6d9d1] bg-white p-3 sans text-sm"><option value="">Assign vehicle</option>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.driverName} · {vehicle.registrationNumber} ({vehicle.type})</option>)}</select></div>; })}</div></section>;
}