'use client';
import { useState } from 'react';
import { ArrowRight, CheckCircle2, Eye, EyeOff, KeyRound, LockKeyhole } from 'lucide-react';

export function ResetPasswordForm() {
  const [show, setShow] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); setMessage(''); const data = Object.fromEntries(new FormData(event.currentTarget)); try { const response = await fetch('/api/auth/reset-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) setError(result.error); else setMessage(result.message); } catch { setError('Something went wrong. Please try again.'); } finally { setLoading(false); } }
  return <div className="auth-panel"><span className="inline-flex rounded-2xl bg-[#e7eadf] p-3 text-[#24584a]"><KeyRound size={22}/></span><h1 className="mt-5 text-4xl text-[#173f35] md:text-5xl">Choose a new password.</h1><p className="sans mt-3 text-base leading-7 text-[#607067]">Use the secure token from your reset email. It expires after 30 minutes.</p>{message&&<p className="mt-5 flex items-center gap-2 rounded-xl bg-[#e2eee7] p-3 sans text-sm text-[#24584a]"><CheckCircle2 size={17}/>{message}</p>}{error&&<p className="mt-5 rounded-xl bg-[#fff0e8] p-3 sans text-sm text-[#9f5938]">{error}</p>}<form onSubmit={submit} className="mt-7 grid gap-4 sans"><label><span className="auth-label"><KeyRound size={15}/>Reset token</span><input name="token" required className="auth-input" placeholder="Paste your reset token"/></label><label><span className="auth-label"><LockKeyhole size={15}/>New password</span><span className="relative block"><input name="password" type={show?'text':'password'} required minLength={8} className="auth-input pr-12" placeholder="At least 8 characters"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#607067]" aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label><button disabled={loading} className="cta-depth inline-flex items-center justify-center gap-2 rounded-xl bg-[#b66b45] px-5 py-3.5 font-bold text-white hover:bg-[#9f5938] disabled:opacity-60">{loading?'Updating...':'Update password'} {!loading&&<ArrowRight size={17}/>}</button></form></div>;
}
